version: "3.8"

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    depends_on:
      - mongo
      - postgres
      - opensearch
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - api

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: resumescreener
      POSTGRES_USER: konam
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  opensearch:
    container_name: opensearch
    image: opensearchproject/opensearch:2.12.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=@Konam12345
volumes:
  mongo_data:
  pgdata:
  opensearch-data:
